routes/web.php
<?php

use App\Http\Controllers\SettingsController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::prefix('settings')->name('settings.')->group(function () {
    Route::get('/', [SettingsController::class, 'index'])->name('index');
    Route::post('/environment/fork', [SettingsController::class, 'forkEnvironment'])->name('environment.fork');
    Route::post('/environment/default', [SettingsController::class, 'setDefaultEnvironment'])->name('environment.default');
    Route::post('/environment/delete', [SettingsController::class, 'deleteEnvironment'])->name('environment.delete');
});

app/Models/AppSettings.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class AppSettings extends Model
{
    use HasFactory;

    protected $connection = 'sqlite_app';
    protected $table = 'settings';

    protected $fillable = [
        'environment',
    ];
}

app/Models/Customer.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Customer extends Model
{
    use HasFactory;

    protected $fillable = [
        'name',
        'balance',
        'age',
    ];
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/SettingsController.php
<?php

namespace App\Http\Controllers;

use App\Helpers\EnvironmentHelper;
use Exception;
use Illuminate\Http\Request;

class SettingsController extends Controller
{
    public function index()
    {
        $default = EnvironmentHelper::default();
        $environments = EnvironmentHelper::getAll();

        return view('settings', [
            'default' => $default,
            'environments' => $environments,
        ]);
    }

    public function forkEnvironment(Request $request)
    {
        $validated = $request->validate([
            'fork_environment' => ['required'],
            'fork_name' => ['required'],
        ]);

        $env = $validated['fork_environment'];
        $name = $validated['fork_name'];

        try {
            EnvironmentHelper::fork($env, $name);
        } catch (Exception $e) {
            session()->flash('error', $e->getMessage());
            return back();
        }

        session()->flash('success', "Environment '$env' forked into '$name'!");

        return back();
    }

    public function setDefaultEnvironment(Request $request)
    {
        $validated = $request->validate([
            'default_name' => ['required'],
        ]);

        $env = $validated['default_name'];

        try {
            EnvironmentHelper::setDefault($env);
        } catch (Exception $e) {
            session()->flash('error', $e->getMessage());
            return back();
        }

        session()->flash('success', "Environment '$env' set as default!");

        return back();
    }

    public function deleteEnvironment(Request $request)
    {
        $validated = $request->validate([
            'delete_name' => ['required'],
        ]);

        $env = $validated['delete_name'];

        try {
            EnvironmentHelper::delete($env);
        } catch (Exception $e) {
            session()->flash('error', $e->getMessage());
            return back();
        }

        session()->flash('success', "Environment '$env' deleted!");

        return back();
    }
}

resources/views/settings.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Environment demo</title>
    <link rel="stylesheet" href="{{ asset('css/app.css') }}">
</head>
<body>
    @if (Session::has('success'))
        <div class="notification success">
            {{ Session::get('success') }}
        </div>
    @endif

    @if (Session::has('error'))
        <div class="notification error">
            {{ Session::get('error') }}
        </div>
    @endif

    <h1>Environment</h1>

    <p>Default: {{ $default }}</p>

    <form action="{{ route('settings.environment.fork') }}" method="post">
        @csrf

        <h2>Fork environment</h2>

        <div>
            <label for="fork_environment">Enviroment:</label>

            <select name="fork_environment" id="fork_environment">
                @foreach ($environments as $env)
                    <option value="{{ $env }}">{{ $env }}</option>
                @endforeach
            </select>

            @error('fork_environment')
                <p class="help">{{ $message }}</p>
            @enderror
        </div>

        <div>
            <label for="fork_name">Name:</label>

            <input type="text" name="fork_name" id="fork_name">

            @error('fork_name')
                <p class="help">{{ $message }}</p>
            @enderror
        </div>

        <div>
            <button type="submit">Fork</button>
        </div>
    </form>

    <hr>

    <form action="{{ route('settings.environment.default') }}" method="post">
        @csrf

        <h2>Default environment</h2>

        <div>
            <label for="default_name">Name:</label>

            <select name="default_name" id="default_name">
                @foreach ($environments as $env)
                    <option value="{{ $env }}">{{ $env }}</option>
                @endforeach
            </select>

            @error('default_name')
                <p class="help">{{ $message }}</p>
            @enderror
        </div>

        <div>
            <button type="submit">Set as default</button>
        </div>
    </form>

    <hr>

    <form action="{{ route('settings.environment.delete') }}" method="post">
        @csrf

        <h2>Delete environment</h2>

        <div>
            <label for="delete_name">Name:</label>

            <select name="delete_name" id="delete_name">
                @foreach ($environments as $env)
                    <option value="{{ $env }}">{{ $env }}</option>
                @endforeach
            </select>

            @error('delete_name')
                <p class="help">{{ $message }}</p>
            @enderror
        </div>

        <div>
            <button type="submit">Delete</button>
        </div>
    </form>
</body>
</html>